site_name: Lime Bootstrap
pages:
  - 'Documentation':
    - 'Introduction': 'index.md'
    - 'Getting started': 'getting_started.md'
    - 'Included components': 'included_components.md'
    - 'Bindnings & filters': 'bindings_and_filters.md'
    - 'Data sources': 'datasources.md'
    - 'Custom components Apps': 'custom_components.md'
    - 'Advanced': 'advanced.md'
  - 'Changelog':
    - 'LBS 2': 'changelog/2.x.md'
    - 'LBS 1': 'changelog/1.x.md'
theme: readthedocs
repo_url: https://github.com/Lundalogik/LimeBootstrap
repo_name: 'Lundalogik/LimeBootstrap'
site_description: Lime Bootstrap documentation
site_author: Lime Technologies AB
docs_dir: docs
dev_addr: localhost:3002
extra_css:
  - 'assets/stylesheets/custom.css'
theme:
  name: 'material'
  custom_dir: 'docs/theme'
  logo:
    icon: 'home'
  feature:
    tabs: true
  palette:
    primary: 'teal'
    accent: 'teal'
  favicon: 'assets/images/favicon.ico'
markdown_extensions:
- codehilite
- admonition
- meta

